name: 'Install Vulkan SDK'
description: 'Install and cache the Vulkan SDK'
inputs:
  version:
    description: 'Vulkan SDK version to install'
    required: false
    default: '1.4.335.0'
outputs:
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.vulkan-sdk-cache.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: restore vulkan sdk cache
      id: vulkan-sdk-cache
      uses: actions/cache/restore@v4
      with:
        path: vulkan-sdk
        key: ${{ runner.os }}-vulkan-sdk-${{ inputs.version }}
    - name: install vulkan sdk
      if: steps.vulkan-sdk-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python "$GITHUB_ACTION_PATH/install-vulkan-sdk.py" ${{ inputs.version }}
        ls vulkan-sdk
    - name: save vulkan sdk cache
      if: steps.vulkan-sdk-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: vulkan-sdk
        key: ${{ runner.os }}-vulkan-sdk-${{ inputs.version }}
    - name: set vulkan sdk env vars
      shell: bash
      run: |
        echo "VULKAN_SDK=${PWD}/vulkan-sdk" >> $GITHUB_ENV
