name: 'Install Mesa'
description: 'Install Mesa'
inputs:
  version:
    description: 'Version of Mesa to install'
    required: false
    default: '25.3.3'
runs:
  using: 'composite'
  steps:
    - name: Install Mesa Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install mesa-utils mesa-utils-extra
        sudo apt-get install libgl1-mesa-dri libglx-mesa0
        sudo apt-get install mesa-vulkan-drivers vulkan-tools

    - name: Install Mesa MacOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install mesa

    - name: Install Mesa Windows
      if: runner.os == 'Windows'
      shell: bash
      run: |
        curl -o mesa.7z https://github.com/pal1000/mesa-dist-win/releases/download/${{ inputs.version }}/mesa3d-${{ inputs.version }}-release-msvc.7z
        7z x mesa.7z -o./mesa
        ./mesa/systemwidedeploy.cmd
      env:
        VULKAN_DRIVER: ${PWD}/mesa/x64/lvp_icd.x86_64.json
