
name: release

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        python-version: ['3.12']
        arch: [x64]

    steps:
    - uses: actions/checkout@v2

    - name: Initialize Submodules
      run: |
        git submodule update --init --recursive

    - name: Set up Python ${{ matrix.python-version }}-${{ matrix.arch }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}

    - name: Install ninja
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Install Poetry
      uses: snok/install-poetry@v1.3.2

    - name: Install
      run: |
        poetry build

    - name: Upload Github Wheel Release Artifact
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./build/*.whl
        file_glob: true
        tag: ${{ github.ref }}

    - name: Upload Wheels to PyPi
      if: github.event_name == 'release'
      run: |
        pipx run twine upload build/* --skip-existing
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

    - name: Build Source
      if: runner.os == 'Linux'
      run: |
        pipx install build
        pipx run build --sdist

    - name: Upload Github Wheel Source Artifact
      if: runner.os == 'Linux' && github.event_name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./dist/*.tar.gz
        file_glob: true
        tag: ${{ github.ref }}

    - name: Upload Source to PyPi
      if: runner.os == 'Linux' && github.event_name == 'release'
      run: |
        pipx run twine upload dist/* --skip-existing
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
