
name: vulkan-sdk

on: [workflow_call]

jobs:
  build:

    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        vulkan-sdk-version: 1.4.335.0

    steps:

    - name: vulkan sdk cache
      id: vulkan-sdk-cache
      uses: actions/cache@v4
      with:
        path: vulkan-sdk
        key: ${{ matrix.os }}-vulkan-sdk-${{ vulkan-sdk-version }}

    - name: install vulkan sdk
      if: steps.vulkan-sdk-cache.outputs.cache-hit != 'true'
      run: |
        python .github/install-vulkan-sdk.py ${{ matrix.vulkan-sdk-version }}
